### ISSUE TITLE
Resourcepack not loading on 1.18 spigot

### ISSUE THREAD

**Issue by GermanGGV** [antoKeinanen/ttvChatPlugin#1]
**Describe the bug**
The resourpack dont work and the emotes be like this []
**To Reproduce**
[e.g.]
1. Open the server
2. Use the emotes

**Expected behavior**
The emotes looks like emotes

**Screenshots**
![image](https://user-images.githubusercontent.com/89332599/144721557-01716373-8a9b-4fbf-9b84-347d1cc30e09.png)

**Server logs**
If applicable, add server logs to help explain your problem.

**Server platform and game version:**
 - platform: [spigot]
 - Version [e.g. 1.18.0]

**Additional context**

**Comment by antoKeinanen** [comment]
Hi! Can you please provide me your server.properties file?

**Comment by GermanGGV** [comment]
I cant send you the file for the extension but here is the text.
#Minecraft server properties
#Sat Dec 04 17:41:19 UTC 2021
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings=
level-name=world
motd=:D
query.port=25565
hellworld=true
pvp=true
texture-pack=
generate-structures=true
difficulty=hard
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
use-native-transport=true
max-players=10
online-mode=false
enable-status=true
allow-flight=false
broadcast-rcon-to-ops=true
view-distance=10
max-build-height=256
server-ip=0.0.0.0
resource-pack-prompt=
allow-nether=true
server-port=27842
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=https://github.com/antoKeinanen/ttvChatPlugin/releases/download/1.0.0/ttvChatTextures-1.0.zip=1
entity-broadcast-range-percentage=100
simulation-distance=10
rcon.password=
player-idle-timeout=0
debug=false
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
snooper-enabled=true
function-permission-level=2
level-type=default
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
resource-pack-sha1=
spawn-protection=0
max-world-size=29999984

**Comment by antoKeinanen** [comment]
Ok you should change this part `resource-pack=https://github.com/antoKeinanen/ttvChatPlugin/releases/download/1.0.0/ttvChatTextures-1.0.zip=1
` to this `resource-pack=https://github.com/antoKeinanen/ttvChatPlugin/releases/download/1.0.0/ttvChatTextures-1.0.zip
`

**Comment by GermanGGV** [comment]
It works, thanks. Is it possible to add more emotes by changing the resource pack or can they only be added by programming?

**Comment by antoKeinanen** [comment]
I need to program them in for now. But I'm thinking of adding a feature for that. If you want any new emote feel free to ask me.
