### ISSUE TITLE
Unicode textures not loading on Mac

### ISSUE THREAD

**Issue by tylerolson** [antoKeinanen/ttvChatPlugin#2]
**Describe the bug**
When attempting to use on Mac version of Minecraft the unicode in chat remains as a black square.

**To Reproduce**
1. Use MacOS

**Server platform and game version:**
 - Latest paper
 - 1.19.3

**Additional context**

**Comment by antoKeinanen** [comment]
Hello! First of all sorry for the long response time. I am not sure but I believe that this issue might be caused by minecraft not loading the font correctly. To fix this try to use optifine or other similar improved render engine.

**Comment by antoKeinanen** [comment]
Closed due to inactivity.
