### ISSUE TITLE
Question about TTV Chat plugin

### ISSUE THREAD

**Issue by Testicx** [antoKeinanen/ttvChatPlugin#3]
I would like to ask if it would be posisble to add custom emotes to this plugin? I can add them myself but am unable to change the name of the emote. Please let me know as soon as possible, would love to help aswell if needed. Thanks in advance!

**Comment by antoKeinanen** [comment]
Hello! Yes adding custom emotes is possible. To do that you need to:
1. Download the picture you want to use as png (I have not tested other formats) and scale it down to 20x20 pixels. Also rename the file to reflect the emote.
2. Put the picture into texture/assets/minecraft/textures/custom
3. Go to texture/assets/minecraft/font and edit default.json. Add the following lines:
    {
      "type": "bitmap",
      "file": "minecraft:custom/PepeHands.png",
      "ascent": 9,
      "height": 9,
      "chars": ["\uE009"]
    }

Just remember to change the char to be unique number field and file field.

4. Goto package me.jm.ttvchat.ttvchat.listeners and add the changes to emotes1 variable. The emotes need to be in the exact same order as in default.json and separated by a comma ",".

If you need more info or want to help by contributing I have a discord server [https://discord.gg/UhZMeE9KqG](https://discord.gg/UhZMeE9KqG). I am sorry my response took a while as I am on holiday and not home.

**Comment by antoKeinanen** [comment]
Added ability to to add custom emotes in the release 2.0.0.
